[versions]
gradle = "7.2.1"
kotlin = "1.7.10"
android = "7.3.0"
core-ktx = "1.7.0"
appcompat = "1.5.1"
material = "1.6.1"
constraintlayout = "2.1.4"
junit = "4.13.2"
test-junit = "1.1.3"
test-espresso-core = "3.4.0"
hilt = "2.43.2"
hilt-compiler = "1.0.0"
timber = "5.0.1"
room = "2.4.3"
coroutine = "1.6.1"
runtimeKtx = "2.4.1"
viewModelKtx = "2.4.1"
activityKtx= "1.5.1"
camerax = "1.1.0-beta02"
activityKtx = "1.5.1"
firebaseBom = "30.5.0"
firestore = "24.4.0"
firebaseStorage = "20.1.0"
paging = "3.1.1"
googleServices = "4.3.14"

[libraries]

android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-junit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso-core" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "runtimeKtx" }
androidx-lifecycle-viewModel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewModelKtx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorage" }

paging = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }

camera-core = {group = "androidx.camera", name = "camera-core", version.ref = "camerax"}
camera-camera2 = {group = "androidx.camera", name = "camera-camera2", version.ref = "camerax"}
camera-lifecycle = {group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax"}
camera-video = {group = "androidx.camera", name = "camera-video", version.ref = "camerax"}
camera-view = {group = "androidx.camera", name = "camera-view", version.ref = "camerax"}
camera-extensions = {group = "androidx.camera", name = "camera-extensions", version.ref = "camerax"}


[bundles]
room = ["room-runtime", "room-ktx"]
room = ["room-runtime","room-ktx"]
cameraX = ["camera-core", "camera-camera2", "camera-lifecycle", "camera-video", "camera-view", "camera-extensions"]



[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-gradle-plugin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-services = {id = "com.google.gms.google-services", version.ref = "googleServices"}